# Generated by Django 3.0.8 on 2020-08-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200814_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo',
            new_name='photoURL',
        ),
        migrations.AddField(
            model_name='listing',
            name='highestBid',
            field=models.FloatField(default=0),
        ),
    ]
