# Generated by Django 3.0.8 on 2020-08-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200815_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photoURL',
            new_name='photoUrl',
        ),
    ]
