# Generated by Django 3.0.8 on 2020-08-15 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='creator',
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userListings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='listed', to='auctions.Listing'),
        ),
    ]
