# Generated by Django 3.0.8 on 2020-08-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200815_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listingId',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listingId',
            new_name='listing',
        ),
    ]
