# Generated by Django 3.0.8 on 2020-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200815_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
