# Generated by Django 3.0.8 on 2020-08-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200816_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.FloatField(blank=True, max_length=11, null=True),
        ),
    ]
