# Generated by Django 3.0.8 on 2020-10-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200816_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlisted', to='auctions.Listing'),
        ),
    ]
